console.log("----------------Q1------------------");
var sweety="Sweety",cutie="Cutie",temp;
console.log("Before swap");
console.log(sweety,cutie);
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("After swap");
console.log(sweety,cutie);

console.log("----------------Q2------------------");
var num1="100",num2="200",num3="300";
console.log("Before swap");
console.log(num1,num2,num3);
var t=num1;
num1=num2;
num2=num3;
num3=t;
console.log("After swap");
console.log(num1,num2,num3);