const fruits_seasonal=["Banana","Orange","Apple","Mango","Water Melon"];
console.log(`Before performing operation array is: ${fruits_seasonal}`);
console.log('----------------------Q1----------------------');
let a=fruits_seasonal[0];
let b=fruits_seasonal[fruits_seasonal.length-1];
console.log(`First and Last element :${a}  ${b}`);
console.log('----------------------Q2----------------------');
fruits_seasonal.unshift("Papaya");
console.log(`After adding element:${fruits_seasonal}`);
console.log('----------------------Q3----------------------');
fruits_seasonal.splice(4,1);
console.log(`After removing element:${fruits_seasonal}`);
console.log('----------------------Q4 Adding element Pineapple at end----------------------');
fruits_seasonal.push("Pineapple");
console.log(fruits_seasonal);
console.log('----------------------Q5 Insert an element Dragon Fruit before Water melon----------------------');
fruits_seasonal.splice(4,0,"Dragon Fruit");
console.log(fruits_seasonal);
console.log('----------------------Q6 Replace element Orange with Kiwi----------------------');
fruits_seasonal.splice(2,1,"Kiwi");
console.log(fruits_seasonal);
console.log('----------------------Q7 log element starting from index 1-4----------------------');
let c=fruits_seasonal.slice(1,5);
console.log(c);
console.log('----------------------Q8 log last 3 element----------------------');
let d=fruits_seasonal.slice(fruits_seasonal.length-3,fruits_seasonal.length);
console.log(d);